// Generated by CoffeeScript 1.6.2
(function() {
  var Levels;

  Levels = (function() {
    function Levels() {}

    Levels.prototype.fatal = {
      name: "Fatal",
      value: 0
    };

    Levels.prototype.error = {
      name: "Error",
      value: 1
    };

    Levels.prototype.warn = {
      name: "Warn",
      value: 2
    };

    Levels.prototype.info = {
      name: "Info",
      value: 3
    };

    Levels.prototype.debug = {
      name: "Debug",
      value: 4
    };

    Levels.prototype.trace = {
      name: "Trace",
      value: 5
    };

    Levels.prototype.toJSON = function() {
      var json;

      json = {
        fatal: {
          name: "Fatal",
          value: 0
        },
        error: {
          name: "Error",
          value: 1
        },
        warn: {
          name: "Warn",
          value: 2
        },
        info: {
          name: "Info",
          value: 3
        },
        debug: {
          name: "Debug",
          value: 4
        },
        trace: {
          name: "Trace",
          value: 5
        }
      };
      return json;
    };

    return Levels;

  })();

  if (typeof module === 'undefined' && typeof window !== 'undefined') {
    window.Levels = Levels;
  } else {
    module.exports = Levels;
  }

}).call(this);
