// Generated by CoffeeScript 1.6.2
(function() {
  var Config;

  Config = (function() {
    function Config() {}

    Config.prototype.max = 10;

    Config.prototype.outputs = ['console'];

    return Config;

  })();

  if (typeof module === 'undefined' && typeof window !== 'undefined') {
    window.Config = Config;
  } else {
    module.exports = Config;
  }

}).call(this);
