// Generated by CoffeeScript 1.6.2
(function() {
  var Levels, Message;

  if (typeof module === 'undefined' && typeof window !== 'undefined') {
    Levels = window.Levels;
  } else {
    Levels = require('./levels');
  }

  Message = (function() {
    function Message(level, message) {
      this.level = level;
      this.message = message;
      this.date = new Date();
      this.levels = new Levels();
    }

    Message.prototype.toString = function() {
      return "" + this.levels[this.level].name + " : " + this.message + " at: " + this.date;
    };

    Message.prototype.toJSON = function() {
      return {
        "level": this.level,
        "message": this.message,
        "label": this.toString(),
        "date": this.date
      };
    };

    return Message;

  })();

  if (typeof module === 'undefined' && typeof window !== 'undefined') {
    window.Message = Message;
  } else {
    module.exports = Message;
  }

}).call(this);
